name: Maven CI

on:
  push:       # Run when you push code
    branches: [ "main" ]
  pull_request:  # Run on pull requests too
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Get your code from GitHub
    - name: Checkout source code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17 for Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build and run tests
    - name: Build with Maven
      run: mvn clean install

